repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
-   repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-err-check # requires github.com/kisielk/errcheck
      - id: golangci-lint # requires github.com/golangci/golangci-lint
