{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name:  {{ include "helm.fullname" . }}
  labels: 
    {{- include "helm.labels" . | nindent 4 }}
    release: prometheus
spec:
  groups:
    - name: {{ include "common.names.fullname" . }}
      rules: {{- include "common.tplvalues.render" ( dict "value" .Values.prometheusRule.rules "context" $ ) | nindent 8 }}
{{- end }}
