apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: container-structure-test
  namespace: default
spec:
  params:
  - description: Image which should be tested
    name: image
    type: string
  - default: quay.io/slauger/container-structure-test-ubi
    name: runtime-image
    type: string
  - default: config.yaml
    description: Config file for the test execution
    name: config
    type: string
  sidecars:
  - args:
    - --storage-driver=vfs
    - --userland-proxy=false
    - --debug
    image: docker.io/docker:dind
    name: server
    readinessProbe:
      exec:
        command:
        - docker
        - info
      periodSeconds: 1
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/docker
      name: dind-storage
    - mountPath: /var/run/
      name: dind-socket
  steps:
  - image: $(params.runtime-image)
    imagePullPolicy: Always
    name: container-structure-test
    resources: {}
    script: |
      #!/bin/sh
      set -xe
      until docker info; do sleep 1; done
      docker pull $(params.image)
      /container-structure-test test --image $(params.image) --config $(workspaces.config.path)/$(params.config)
    volumeMounts:
    - mountPath: /var/lib/docker
      name: dind-storage
    - mountPath: /var/run/
      name: dind-socket
  volumes:
  - emptyDir: {}
    name: dind-storage
  - emptyDir: {}
    name: dind-socket
  workspaces:
  - description: The workspace where the tests are stored
    name: config
