kind: ClusterTask
apiVersion: tekton.dev/v1alpha1
metadata:
  annotations:
    tekton.dev/categories: Image Build
    tekton.dev/displayName: Build and upload container image using Kaniko
    tekton.dev/pipelines.minVersion: 0.17.0
    tekton.dev/platforms: linux/amd64
    tekton.dev/tags: image-build
  labels:
    app.kubernetes.io/version: '0.6'
  name: kaniko
spec:
  description: >-
    This Task builds a simple Dockerfile with kaniko and pushes to a registry.
    This Task stores the image name and digest as results, allowing Tekton
    Chains to pick up that an image was built & sign it.
  params:
    - description: Name (reference) of the image to build.
      name: IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: ./
      description: The build context used by Kaniko.
      name: CONTEXT
      type: string
    - default: []
      name: EXTRA_ARGS
      type: array
    - default: >-
        gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5
      description: The image on which builds will run (default is v1.5.1)
      name: BUILDER_IMAGE
      type: string
  results:
    - description: Digest of the image just built.
      name: IMAGE_DIGEST
    - description: URL of the image just built.
      name: IMAGE_URL
  steps:
    - args:
        - $(params.EXTRA_ARGS)
        - '--dockerfile=$(params.DOCKERFILE)'
        - '--context=$(workspaces.source.path)/$(params.CONTEXT)'
        - '--destination=$(params.IMAGE)'
        - '--digest-file=$(results.IMAGE_DIGEST.path)'
      image: $(params.BUILDER_IMAGE)
      name: build-and-push
      resources: {}
      securityContext:
        runAsUser: 0
      workingDir: $(workspaces.source.path)
    - image: >-
        docker.io/library/bash:5.1.4@sha256:b208215a4655538be652b2769d82e576bc4d0a2bb132144c060efc5be8c3f5d6
      name: write-url
      resources: {}
      script: |
        set -e
        image="$(params.IMAGE)"
        echo "${image}" | tee "$(results.IMAGE_URL.path)"
  workspaces:
    - description: Holds the context and Dockerfile
      name: source
    - description: Includes a docker `config.json`
      mountPath: /kaniko/.docker
      name: dockerconfig
      optional: true
